FROM rust

WORKDIR /usr/src

COPY client client
COPY network network
COPY simple_db simple_db

WORKDIR /usr/src/client

# RUN cargo install --profile release --path  .

RUN cargo install --path  .

ENV RUST_LOG=info

CMD [ "client" ]
