[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.6"
log = "0.4.25"
tokio = "1.43.0"
simple_db = { path = "../simple_db" }
bincode = "1.3.3"
omnipaxos = "0.2.2"
serde = "1.0.217"
